---
title: C28163 | Microsoft Docs
ms.custom: ''
ms.date: 11/15/2016
ms.prod: visual-studio-dev14
ms.reviewer: ''
ms.suite: ''
ms.technology:
- vs-devops-test
ms.tgt_pltfrm: ''
ms.topic: article
f1_keywords:
- C28163
helpviewer_keywords:
- C28163
ms.assetid: 24fecbde-1c96-4a45-82f7-9f47cfc0ef11
caps.latest.revision: 5
author: mikeblome
ms.author: mblome
manager: ghogen
ms.openlocfilehash: ea546ce0fd1540ef5a193a8e61271bfa187e1a5c
ms.sourcegitcommit: af428c7ccd007e668ec0dd8697c88fc5d8bca1e2
ms.translationtype: MT
ms.contentlocale: es-ES
ms.lasthandoff: 11/16/2018
ms.locfileid: "51762570"
---
# <a name="c28163"></a>C28163
[!INCLUDE[vs2017banner](../includes/vs2017banner.md)]

Advertencia C28163: la función nunca debe llamarse desde dentro de un bloque try / except bloque  
  
 Esta advertencia se muestra cuando es una función de un tipo que nunca debe incluirse en un `try/except` bloque se encuentra en un `try/except` bloque. La herramienta de análisis de código encuentra al menos una ruta de acceso en el que la función llamada estaba dentro de un `try/except` bloque.



