---
title: C6320
ms.date: 11/04/2016
ms.prod: visual-studio-dev15
ms.technology: vs-ide-code-analysis
ms.topic: reference
f1_keywords:
- C6320
helpviewer_keywords:
- C6320
ms.assetid: fb9e568e-b3d4-4ce2-a276-a64ad74d7b1e
author: mikeblome
ms.author: mblome
manager: wpickett
ms.workload:
- multiple
ms.openlocfilehash: 5c8d62a439816f95a6f8652123770e160787bf28
ms.sourcegitcommit: e13e61ddea6032a8282abe16131d9e136a927984
ms.translationtype: MT
ms.contentlocale: es-ES
ms.lasthandoff: 04/26/2018
ms.locfileid: "31890897"
---
# <a name="c6320"></a>C6320
Advertencia C6320: expresión de filtro de excepciones es la constante EXCEPTION_EXECUTE_HANDLER. Esto puede enmascarar excepciones que no se han diseñado para controlar

 Esta advertencia indica que el efecto secundario de utilizar la constante EXCEPTION_EXECUTE_HANDLER en un bloque __except. En este caso, la instrucción en el \_siempre se ejecutará el bloque _except para controlar la excepción, incluidas las excepciones que desea controlar en una función determinada. Se recomienda que compruebe la excepción antes de controlarla.

## <a name="example"></a>Ejemplo
 El código siguiente genera esta advertencia porque el bloque __except intentará controlar las excepciones de todos los tipos:

```
#include <stdio.h>
#include <excpt.h>

void f(int *p)
{
   __try
   {
      puts("in try");
      *p = 13;  // might cause access violation exception
      // code ...
   }
   __except(EXCEPTION_EXECUTE_HANDLER) // warning
   {
      puts("in except");
      // code ...
   }
}
```

 Para corregir esta advertencia, utilice `GetExceptionCode` para comprobar si una excepción determinada antes de controlarla, como se muestra en el código siguiente:

```
#include <stdio.h>
#include <windows.h>
#include <excpt.h>

void f(int *p)
{
   __try
   {
      puts("in try");
      *p = 13;    // might cause access violation exception
      // code ...
   }
   __except(GetExceptionCode()==EXCEPTION_ACCESS_VIOLATION ?
               EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH)
   {
      puts("in except");
      // code ...
   }
}
```

## <a name="see-also"></a>Vea también
 [try-except (Instrucción)](/cpp/cpp/try-except-statement)