---
title: 'CA2124: Incluir cláusulas finally vulnerables en un bloque try externo'
description: En las versiones 1,0 y 1,1 del .NET Framework, un método público o protegido contiene un bloque try/catch/finally. El bloque Finally aparece para restablecer el estado de seguridad y no se incluye en un bloque Finally.
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- CA2124
- WrapVulnerableFinallyClausesInOuterTry
helpviewer_keywords:
- CA2124
- WrapVulnerableFinallyClausesInOuterTry
ms.assetid: 82efd224-9e60-4b88-a0f5-dfabcc49a254
author: mikejo5000
ms.author: mikejo
manager: jmartens
ms.workload:
- multiple
ms.openlocfilehash: ab236c2bfa37752e29c5b4179025837b9843f280
ms.sourcegitcommit: 8590cf6b3351e82827fd21159beefef0c02bf162
ms.translationtype: MT
ms.contentlocale: es-ES
ms.lasthandoff: 03/08/2021
ms.locfileid: "102469007"
---
# <a name="ca2124-wrap-vulnerable-finally-clauses-in-outer-try"></a>CA2124: Incluir cláusulas finally vulnerables en un bloque try externo

|Elemento|Valor|
|-|-|
|RuleId|CA2124|
|Category|Microsoft.Security|
|Cambio importante|Poco problemático|

## <a name="cause"></a>Causa
En las versiones 1,0 y 1,1 del .NET Framework, un método público o protegido contiene un `try` / `catch` / `finally` bloque. El `finally` bloque parece restablecer el estado de seguridad y no se incluye en un `finally` bloque.

> [!NOTE]
> Esta regla está en desuso. Para obtener más información, consulte [reglas en desuso](fxcop-unported-deprecated-rules.md).

## <a name="rule-description"></a>Descripción de la regla
Esta regla ubica `try` / `finally` los bloques en código que tienen como destino las versiones 1,0 y 1,1 del .NET Framework que podrían ser vulnerables a los filtros de excepciones malintencionados presentes en la pila de llamadas. Si se producen operaciones confidenciales como la suplantación en el bloque try y se produce una excepción, el filtro se puede ejecutar antes que el `finally` bloque. En el ejemplo de suplantación, esto significa que el filtro se ejecutaría como el usuario suplantado. Los filtros solo se pueden implementar en Visual Basic.

> [!NOTE]
> En las versiones 2,0 y posteriores del .NET Framework, el motor en tiempo de ejecución protege automáticamente un `try` / `catch` /  `finally` bloque de los filtros de excepciones malintencionados, si el restablecimiento se produce directamente dentro del método que contiene el bloque de excepción.

## <a name="how-to-fix-violations"></a>Cómo corregir infracciones
Coloque el desencapsulado `try` / `finally` en un bloque try externo. Vea el segundo ejemplo siguiente. Esto obliga `finally` a que se ejecute antes de filtrar el código.

## <a name="when-to-suppress-warnings"></a>Cuándo suprimir advertencias
No suprima las advertencias de esta regla.

## <a name="pseudo-code-example"></a>Ejemplo de pseudocódigo

### <a name="description"></a>Descripción

El pseudocódigo siguiente muestra el patrón que detecta esta regla.

```csharp
try {
   // Do some work.
   Impersonator imp = new Impersonator("John Doe");
   imp.AddToCreditCardBalance(100);
}
finally {
   // Reset security state.
   imp.Revert();
}
```

En el siguiente pseudocódigo se muestra el patrón que puede usar para proteger el código y satisfacer esta regla.

```csharp
try {
     try {
        // Do some work.
     }
     finally {
        // Reset security state.
     }
}
catch()
{
    throw;
}
```
